/* eslint-disable import/no-anonymous-default-export */
export default {
    CREATE_POST: "CREATE_POST",
    LOAD_POSTS_PUBLISHED: "LOAD_POSTS_PUBLISHED",
    LOAD_POSTS_UNPUBLISH: "LOAD_POSTS_UNPUBLISH",
    LOAD_POST_BY_ID: "LOAD_POST_BY_ID",
    UPDATE_POST: "UPDATE_POST",
    PUBLISH_POST: "PUBLISH_POST",
    DELETE_POST: "DELETE_POST",
    CREATE_COMMENT: "CREATE_COMMENT",
    APPROVE_COMMENT: "APPROVE_COMMENT",
    DELETE_COMMENT: "DELETE_COMMENT",
};